load("//bazel:build.bzl", "app_image")

app_image(
    base = "@img-zookeeper//image",
    cmd = [""],
    entrypoint = [
        "/bin/zookeeper",
    ],
    files = [
    ],
    layers = [
    ],
    ports = ["2181/tcp"],
    tag = "latest",
    tars = [
    ],
)
